# .github/workflows/deploy.yml
name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_PROD_CREDENTIALS }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Package Backend
        working-directory: backend
        run: |
          rm -rf backend_env
          zip -r ../deploy.zip *

      - name: Debug Secrets
        run: |
          echo "Subscription ID: ${{ vars.AZURE_PROD_SUBSCRIPTION_ID }}"
          echo "Resource Group: ${{ vars.AZURE_PROD_RESOURCE_GROUP }}"
          echo "Web App Name: ${{ vars.AZURE_PROD_WEBAPP_NAME }}"

      - name: Deploy to Azure
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            set -e
            if [ ! -f deploy.zip ]; then
              echo "deploy.zip not found"
              exit 1
            fi
            az webapp deploy \
              --subscription ${{ vars.AZURE_PROD_SUBSCRIPTION_ID }} \
              --resource-group ${{ vars.AZURE_PROD_RESOURCE_GROUP }} \
              --name ${{ vars.AZURE_PROD_WEBAPP_NAME }} \
              --src-path deploy.zip \
              --type zip \
              --async true




              az ad sp create-for-rbac --name "webgpt0-2wc73ir547bl4" --role contributor --scopes /subscriptions/e261fb0a-3d87-49c1-8d3c-32b2bc93b6ff/resourceGroups/rg-SalesFactoryEmpolyees/providers/Microsoft.Web/sites/webgpt0-2wc73ir547bl4 --json-auth
