# .github/workflows/deploy.yml
name: Build and Deploy to Azure

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install System Dependencies
      - name: Install System Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          zip \
          libpango-1.0-0 \
          libharfbuzz0b \
          libpangoft2-1.0-0 \
          libharfbuzz-subset0 \
          libffi-dev \
          libjpeg-dev \
          libopenjp2-7-dev \
          libglib2.0-0 \
          libglib2.0-dev \
          libcairo2 \
          libcairo2-dev \
          libpangocairo-1.0-0 \
          pkg-config \
          python3-dev \
          python3-cffi \
          libgobject-2.0-0

      # 3. Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 5. Build Frontend
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # 6. Package Backend
      - name: Package Backend
        working-directory: backend
        run: |
          rm -rf backend_env
          zip -r ../deploy.zip *
      - name: Debug Secrets
        run: |
          echo "Subscription ID: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}"
          echo "Resource Group: ${{ secrets.AZURE_PROD_RESOURCE_GROUP }}"
          echo "Web App Name: ${{ secrets.AZURE_PROD_WEBAPP_NAME }}"

      # 7. Deploy to Azure
      - name: Deploy to Azure
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            set -e
            if [ ! -f deploy.zip ]; then
              echo "deploy.zip not found"
              exit 1
            fi
            az webapp deploy \
              --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --name ${{ secrets.AZURE_WEBAPP_NAME }} \
              --src-path deploy.zip \
              --type zip \
              --async true
